apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations: 
    argocd.argoproj.io/sync-options: Validate=false
  name: limits
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 65Mi
      limits: 
        cpu: 120m
        memory: 100Mi
