apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx 
  labels: # these are replicaset labels
    app: nginx 
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    # these are use to select the pod to create replicas
    matchLabels:
      tier: frontend
      app: nginx
      # this is pod definition
  template:
    metadata:
    # these labels belongs to pod
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: php-redis
        image: us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5
